Ayomi/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('FirstApp/', include('FirstApp.urls')),
]

FirstApp/urls.py
from django.urls import re_path, path
from FirstApp import views

app_name = 'FirstApp'

urlpatterns = [
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^user/(?P<pk>\d+)/profile/$', views.profile, name='profile'),
    # re_path(r'^user/(?P<pk>\d+)/profile/update/$', views.profile_update, name='profile_update'),
    re_path(r"^logout/$", views.logout, name='logout'),
    path('index/', views.index),
]

FirstApp/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                related_name='profile')

    class Meta:
        verbose_name = 'User profile'

    def __str__(self):
        # return self.user.__str__()
        return "{}".format(self.user.__str__())

FirstApp/views.py
from typing import re

from django.shortcuts import render, get_object_or_404
# from requests import models

from .MyForms import RegistrationForm, LoginForm, ProfileForm
from .models import UserProfile
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import auth
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    print("index doing")
    return HttpResponse("index OK")


@login_required
def profile(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        form = ProfileForm(request.POST)

        if form.is_valid():
            user.email = form.cleaned_data['email']
            user.save()

            return HttpResponseRedirect(reverse('FirstApp:profile', args=[user.id]))
    else:
        default_data = {'email': user.email, }
        form = ProfileForm(default_data)
    return render(request, 'users/profile.html', {'form': form, 'user': user})


# @login_required
# def profile_update(request, pk):
#     user = get_object_or_404(User, pk=pk)
#     # user_profile = get_object_or_404(UserProfile, user=user)
#
#     if request.method == 'POST':
#         form = ProfileForm(request.POST)
#
#         if form.is_valid():
#             user.email = form.cleaned_data['email']
#             user.save()
#
#             return HttpResponseRedirect(reverse('FirstApp:profile', args=[user.id]))
#     else:
#         default_data = {'email': user.email, }
#         form = ProfileForm(default_data)
#
#     return render(request, 'users/profile_update.html', {'form': form, 'user': user})


def register(request):
    if request.method == 'POST':

        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password2']

            user = User.objects.create_user(username=username, password=password, email=email)

            user_profile = UserProfile(user=user)
            user_profile.save()

            return HttpResponseRedirect("/FirstApp/login/")
    else:
        form = RegistrationForm()
    return render(request, 'users/registration.html', {'form': form})


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = auth.authenticate(username=username, password=password)

            if user is not None and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('FirstApp:profile', args=[user.id]))
            else:
                return render(request, 'users/login.html',
                              {'form': form, 'message': 'Mot de passe incorrect, veuillez réessayer'})
    else:
        form = LoginForm()

    return render(request, 'users/login.html', {'form': form})


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect("/FirstApp/login/")

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      {% block title %}
          <title>base</title>
      {% endblock %}

    <link href="/static/bootstrap-4.5.2/dist/css/bootstrap.min.css" rel="stylesheet">

      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>


        <link rel="stylesheet" href="/static/CSS/base.css">

      {% block css %}
      {% endblock %}
  </head>
  <body>



  <div class="container my-con">
        {% block content %}
        {% endblock %}
  </div>

    <script src="/static/JS/jquery-3.5.1.js"></script>
    <script src="/static/bootstrap-4.5.2/dist/js/bootstrap.min.js"></script>

    {% block scripts %}
    {% endblock %}

  </body>
</html>

templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}<h1 class="my-con1">Page de connexion</h1>{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static '/CSS/login.css' %}">
{% endblock %}


{% block content %}

    {% if message %}
    {{ message }}
    {% endif %}
    <div class="form-group">
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                    {{ field.errors }}
                    <label>{{ field.label_tag }}</label>
                    {{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
            </div>
            {% endfor %}
            <input type="submit" value="Se connecter">
        </form>
        <h2 class="my-href">
            <a href="/FirstApp/register" >Retour à la page d'inscription</a>
        </h2>

    </div>

{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}<h1 class="my-con1">Page d'informations utilisateur</h1>{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static '/CSS/profile.css' %}">
{% endblock %}

{% block content %}
    <div class="body">

        <h2 class="title-style">Informations de {{ user.username }}</h2>
{#        <ul class="b1">#}
{#            <li>Email: {{ user.email }}</li>#}
{#        </ul>#}
        <h5 class="b1">Email: {{ user.email }}</h5>


        <h2 class="title-style">
            {% if user.is_authenticated %}
{#                <a href="{% url 'FirstApp:profile_update' user.id %}" class="m1">Edit</a>#}
                <button type="submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Modifier</button>
            {% endif %}
        </h2>

        <h2 class="title-style">
            {% if user.is_authenticated %}
                <a href="{% url 'FirstApp:logout'%}" class="m2">Se déconnecter</a>
            {% endif %}
        </h2>

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modifier mes informations</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
              <div class="form-wrapper">
                  <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="fieldWrapper">
                            {{ field.errors }}
                            <label>{{ field.label_tag }}</label>
                            {{ field }}
                            {% if field.help_text %}
                                <p class="help">{{ field.help_text|safe }}</p>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="button-wrapper submit">
{#                        <input type="submit" value="Update">#}
                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                    </div>
                  </form>
{#                    <label for="lastname" class="col-sm-3 control-label">Email</label>#}
{#                    <input type="text" class="form-control" placeholder="Enter your new email">#}
              </div>
              </div>
{#              <div class="modal-footer">#}
{#                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>#}
{#                <button type="submit" class="btn btn-primary">Save changes</button>#}
{#              </div>#}
            </div>
          </div>
        </div>
    </div>



{% endblock %}

templates/users/profile_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <h1 class="my-con1">Account Profile Info Update Page</h1>
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static '/CSS/profile_update.css' %}">
{% endblock %}


{% block content %}
    <div class="body">
        <h2 class="title-style">Account Info</h2>
        <ul class="b1">
            <li>Username: {{ user.username }}</li>
        </ul>

        <h2 class="title-style">Update My Profile</h2>
        <div class="form-wrapper">
            <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="fieldWrapper">
                    {{ field.errors }}
                    {{ field.label_tag }}{{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <div class="button-wrapper submit">
                <input type="submit" value="Update">
            </div>
            </form>
        </div>
        <h2 class="title-style">
            <a href="{% url 'FirstApp:logout' %}" class="m1">Logout</a>
        </h2>
    </div>

{% endblock %}

templates/users/registration.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <h1 class="my-con1">Page d'inscription</h1>
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static '/CSS/registration.css' %}">
{% endblock %}

{% block content %}
<div class="body">
    <h2 class="title-style">Inscription</h2>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="b1">
                {{ field.errors }}
                <label>{{ field.label_tag }}</label>
                {{ field }}
                {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
             </div>
        {% endfor %}
            <input type="submit" value="S'inscrire">
    </form>
</div>
{% endblock %}